package org.apache.flink.streaming.examples.partitioning.util;

public class WordCountPartitionData {
	public static final String[] WORDS = new String[]{
		"To be, or not to be, that is the question",
		"Whether 'tis nobler in the mind to suffer",
		"The slings and arrows of outrageous fortune",
		"Or to take arms against a sea of troubles,",
		"And by opposing end them? To die, to sleep,",
		"No more; and by a sleep to say we end"
	};

	public static final String[] FEW_WORDS = new String[]{
		"To be or not to be that is the question",
		"To be or not to be"
	};

	public static final String[] WORDS_SKEW = new String[]{
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"To be, or not to be, that is the question",
		"Whether 'tis nobler in the mind to suffer",
		"The slings and arrows of outrageous fortune",
		"Or to take arms against a sea of troubles,",
		"And by opposing end them? To die, to sleep,",
		"No more; and by a sleep to say we end"
	};
}
